from openstix.providers._base import DatasetConfig, JSONSourceConfig, ProviderConfig, ZIPSourceConfig

config = ProviderConfig(
    name="oasis-open",
    datasets=[
        DatasetConfig(
            name="locations",
            sources=[
                JSONSourceConfig(
                    url="https://api.github.com/repos/oasis-open/cti-stix-common-objects/contents/objects/location"
                ),
            ],
        ),
        DatasetConfig(
            name="industries",
            sources=[
                JSONSourceConfig(
                    url="https://api.github.com/repos/oasis-open/cti-stix-common-objects/contents/objects/identity"
                ),
            ],
        ),
        DatasetConfig(
            name="vulnerabilities",
            sources=[
                ZIPSourceConfig(
                    url="https://github.com/oasis-open/cti-stix-common-objects/archive/refs/heads/main.zip",
                    content_paths="objects/vulnerability",
                ),
            ],
        ),
        DatasetConfig(
            name="tlp20",
            sources=[
                JSONSourceConfig(
                    url="https://api.github.com/repos/oasis-open/cti-stix-common-objects/contents/objects/marking-definition"
                ),
            ],
        ),
    ],
)
