name: Check Pull Request

on: [ pull_request ]

permissions: read-all

jobs:
  ruff:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1