name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Hatch
        run: pip install -U hatch

      - name: Build
        run: hatch -v build

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist
          if-no-files-found: error

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs:
    - build
    environment:
      name: releases
      url: https://pypi.org/project/openstix
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          # body: |
          #   Changes in this Release
          #   - See [CHANGELOG.md](CHANGELOG.md) for details