name: New Release

on:
  push:
    tags:
      - v*

permissions: read-all

jobs:
  build:
    name: Build release
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Hatch
        run: pip install -U hatch

      - name: Build package
        run: hatch -v build

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist
          if-no-files-found: error

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs:
    - build
    environment:
      name: releases
      url: https://pypi.org/project/openstix
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: dist

      - name: Publish package distributions
        uses: pypa/gh-action-pypi-publish@v1.8.10
